project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResult.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutState.as_view()),
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
]

handler403 = 'common.views.error403'

project/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^list/$', views.IndexView.as_view(), name='index'),
    url(r'^folders/(?P<folder_id_or_root>root|[0-9]+)/$', views.ShowFolderView.as_view(), name='show_folder'),
    url(r'^folders/(?P<folder_id_or_root>root|[0-9]+)/create-folder/$', views.CreateFolderView.as_view(), name='create_folder'),
    url(r'^folders/(?P<folder_id_or_root>root|[0-9]+)/create-user/$', views.CreateUserView.as_view(), name='create_user'),
    url(r'^folders/(?P<folder_id_or_root>root|[0-9]+)/mass-registration/$', views.CreateUsersMassView.as_view(), name='create_users_mass'),
    url(r'^delete/$', views.DeleteUsersView.as_view(), name='delete'),
    url(r'^move/$', views.MoveUsersView.as_view(), name='move'),

    # single user profile
    url(r'^(?P<user_id>[0-9]+)/$', views.ProfileShowView.as_view(), name='profile_show'),
    url(r'^(?P<user_id>[0-9]+)/update/$', views.ProfileUpdateView.as_view(), name='profile_update'),
    url(r'^(?P<user_id>[0-9]+)/password/$', views.ProfilePasswordView.as_view(), name='profile_password'),
    url(r'^(?P<user_id>[0-9]+)/permissions/$', views.ProfilePermissionsView.as_view(), name='profile_permissions'),
]

project/users/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm

from common.mptt_fields import OrderedTreeNodeChoiceField

from models import UserFolder, UserProfile


class MassUserInitForm(forms.Form):
    tsv = forms.CharField(widget=forms.Textarea, required=False)


class MassUserPasswordForm(forms.Form):
    password = forms.CharField(required=True)


class MassUserSingleForm(forms.Form):
    username = forms.CharField()
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)


class CreateFolderForm(forms.Form):
    name = forms.CharField(label=_('Folder name'), widget=forms.TextInput(attrs={'autofocus': 'autofocus'}))


class CreateUserForm(UserCreationForm):
    pass


class CreateUsersMassForm(forms.Form):
    tsv = forms.CharField(widget=forms.Textarea, required=True,
                          label=_('Data about users'),
                          help_text=_(u'Lines in the format of “[username] [last name] [first name]” or “[username] [last name] [first name] [patronymic]”.'))
    password = forms.CharField(required=True, label=_('Password'))

    def clean_tsv(self):
        data = self.cleaned_data['tsv']
        user_model = auth.get_user_model()
        users = []

        usernames = set()

        for number, line in enumerate(data.split('\n')):
            line = line.strip()
            if not line:
                continue
            tokens = line.split()
            if len(tokens) == 3:
                username, last_name, first_name = tokens
                patronymic = ''
            elif len(tokens) == 4:
                username, last_name, first_name, patronymic = tokens
            else:
                raise forms.ValidationError(_(u'Line %(number)s does not match the template.'),
                                            code='tokens', params={'number': number + 1})

            if username in usernames:
                raise forms.ValidationError(_(u'User “%(username)s” is listed more than once.'),
                                            code='duplicate', params={'username': username})
            usernames.add(username)

            user = user_model(username=username, first_name=first_name, last_name=last_name)
            userprofile = UserProfile(patronymic=patronymic, needs_change_password=True, folder=None)
            users.append((user, userprofile))

        return users

    def clean(self):
        super(CreateUsersMassForm, self).clean()
        password = self.cleaned_data.get('password')
        users = self.cleaned_data.get('tsv')

        if password is not None and users is not None:
            errors = []
            for user, userprofile in users:
                try:
                    user.set_password(password)
                    user.full_clean()

                    userprofile.full_clean(exclude=['user'])
                except forms.ValidationError as e:
                    print e
                    errors.append(forms.ValidationError(u'{0}: {1}'.format(user.username, u' '.join(e.messages))))
            if errors:
                raise forms.ValidationError(errors)


class MoveUsersForm(forms.Form):
    folder = OrderedTreeNodeChoiceField(label=_('Destination folder'), queryset=UserFolder.objects.all(), required=False)

'''
User search
'''


class UserSearchForm(forms.Form):
    query = forms.CharField(required=False)
    staff = forms.BooleanField(label=_('Staff only'), required=False)


'''
User profile
'''


class UserForm(forms.ModelForm):
    class Meta:
        model = auth.get_user_model()
        fields = ['is_active', 'username', 'email', 'last_name', 'first_name']


class UserProfileForm(forms.ModelForm):
    folder = OrderedTreeNodeChoiceField(label=_('Folder'), queryset=UserFolder.objects.all(), required=False)

    class Meta:
        model = UserProfile
        fields = ['patronymic', 'folder', 'needs_change_password', 'description']

        help_texts = {
            'needs_change_password': _('User will see a warning message until he sets a new password. '
                                       'This prevents usage of insecure default passwords.')
        }


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = auth.get_user_model()
        fields = ['is_staff']


class UserProfilePermissionsForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['has_api_access']

        help_texts = {
            'has_api_access': _('For service accounts used by the testing module.')
        }

project/users/views.py
import operator

from django.contrib import auth
from django.db import transaction
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, redirect
from django.utils.translation import ugettext_lazy as _
from django.views import generic

from cauth.mixins import StaffMemberRequiredMixin
from common.folderutils import lookup_node_ex, cast_id
from common.pageutils import paginate
from common.views import IRunnerListView, MassOperationView

import forms
from models import UserFolder, UserProfile


class IndexView(StaffMemberRequiredMixin, generic.View):
    template_name = 'users/index.html'
    paginate_by = 12

    def get_queryset(self, query=None, staff=False):
        queryset = auth.get_user_model().objects.all().select_related('userprofile').select_related('userprofile__folder')

        if query is not None:
            terms = query.split()
            if terms:
                search_args = []
                for term in terms:
                    search_args.append(Q(username__icontains=term) | Q(first_name__icontains=term) | Q(last_name__icontains=term))

                queryset = queryset.filter(reduce(operator.and_, search_args))

        if staff:
            queryset = queryset.filter(is_staff=True)

        queryset = queryset.order_by('id')
        return queryset

    def get(self, request):
        form = forms.UserSearchForm(request.GET)
        if form.is_valid():
            queryset = self.get_queryset(form.cleaned_data['query'], form.cleaned_data['staff'])
        else:
            queryset = self.get_queryset()

        context = paginate(request, queryset, self.paginate_by)
        context['active_tab'] = 'search'
        context['form'] = form
        return render(request, self.template_name, context)


class UserFolderMixin(object):
    def get_context_data(self, **kwargs):
        context = super(UserFolderMixin, self).get_context_data(**kwargs)
        cached_trees = UserFolder.objects.all().get_cached_trees()
        node_ex = lookup_node_ex(self.kwargs['folder_id_or_root'], cached_trees)

        context['cached_trees'] = cached_trees
        context['folder'] = node_ex.object
        context['folder_id'] = node_ex.folder_id
        context['active_tab'] = 'folders'
        return context


class ShowFolderView(StaffMemberRequiredMixin, UserFolderMixin, IRunnerListView):
    template_name = 'users/folder.html'
    paginate_by = 50

    def get_context_data(self, **kwargs):
        context = super(ShowFolderView, self).get_context_data(**kwargs)

        folder = context['folder']

        has_users = (self.get_queryset().count() > 0)
        can_delete_folder = (not has_users) and (folder is not None) and (folder.get_descendant_count() == 0)

        context['has_users'] = has_users
        context['can_delete_folder'] = can_delete_folder
        return context

    def get_queryset(self):
        folder_id = cast_id(self.kwargs['folder_id_or_root'])
        return auth.get_user_model().objects.filter(userprofile__folder_id=folder_id)


class CreateFolderView(StaffMemberRequiredMixin, UserFolderMixin, generic.FormView):
    template_name = 'users/create_form.html'
    form_class = forms.CreateFolderForm

    def get_context_data(self, **kwargs):
        context = super(CreateFolderView, self).get_context_data(**kwargs)
        context['form_name'] = _('Create folder')
        return context

    def form_valid(self, form):
        folder_id_or_root = self.kwargs['folder_id_or_root']
        folder_id = cast_id(folder_id_or_root)
        UserFolder.objects.create(name=form.cleaned_data['name'], parent_id=folder_id)
        return redirect('users:show_folder', folder_id_or_root)


class CreateUserView(StaffMemberRequiredMixin, UserFolderMixin, generic.FormView):
    template_name = 'users/create_form.html'
    form_class = forms.CreateUserForm

    def get_context_data(self, **kwargs):
        context = super(CreateUserView, self).get_context_data(**kwargs)
        context['form_name'] = _('Create user')
        return context

    def form_valid(self, form):
        folder_id_or_root = self.kwargs['folder_id_or_root']
        folder_id = cast_id(folder_id_or_root)
        with transaction.atomic():
            user = form.save()
            profile = user.userprofile
            profile.folder_id = folder_id
            profile.save()
        return redirect('users:show_folder', folder_id_or_root)


class CreateUsersMassView(StaffMemberRequiredMixin, UserFolderMixin, generic.FormView):
    template_name = 'users/create_form.html'
    form_class = forms.CreateUsersMassForm
    initial = {'password': '11111'}

    def get_context_data(self, **kwargs):
        context = super(CreateUsersMassView, self).get_context_data(**kwargs)
        context['form_name'] = _('Mass user registration')
        return context

    def form_valid(self, form):
        folder_id_or_root = self.kwargs['folder_id_or_root']
        folder_id = cast_id(folder_id_or_root)
        users = form.cleaned_data['tsv']
        with transaction.atomic():
            for user, userprofile in users:
                user.save()
                userprofile.user = user
                userprofile.folder_id = folder_id
                userprofile.save()
        return redirect('users:show_folder', folder_id_or_root)


class DeleteUsersView(StaffMemberRequiredMixin, MassOperationView):
    template_name = 'users/delete.html'

    def get_queryset(self):
        return auth.get_user_model().objects

    def perform(self, queryset, form):
        queryset.delete()


class MoveUsersView(StaffMemberRequiredMixin, MassOperationView):
    template_name = 'users/move.html'
    form_class = forms.MoveUsersForm

    def get_queryset(self):
        return UserProfile.objects.select_related('user')

    def perform(self, queryset, form):
        folder = form.cleaned_data['folder']
        queryset.update(folder=folder)


class BaseProfileView(StaffMemberRequiredMixin):
    tab = None

    def get_context_data(self, **kwargs):
        context = {
            'edited_user': self.user,
            'edited_profile': self.user.userprofile,
            'active_tab': self.tab,
        }
        context.update(kwargs)
        return context

    def dispatch(self, request, user_id, *args, **kwargs):
        user = get_object_or_404(auth.get_user_model(), pk=user_id)
        self.user = user
        return super(BaseProfileView, self).dispatch(request, user, *args, **kwargs)


class ProfileShowView(BaseProfileView, generic.View):
    tab = 'show'
    template_name = 'users/profile_show.html'

    def get(self, request, user):
        context = self.get_context_data()
        return render(request, self.template_name, context)


class ProfileTwoFormsView(BaseProfileView, generic.View):
    user_form_class = None
    userprofile_form_class = None

    def get(self, request, user):
        user_form = self.user_form_class(instance=user)
        userprofile_form = self.userprofile_form_class(instance=user.userprofile)
        return render(request, self.template_name, self.get_context_data(user_form=user_form, userprofile_form=userprofile_form))

    def post(self, request, user):
        user_form = self.user_form_class(request.POST, instance=user)
        userprofile_form = self.userprofile_form_class(request.POST, instance=user.userprofile)

        if user_form.is_valid() and userprofile_form.is_valid():
            with transaction.atomic():
                user_form.save()
                userprofile_form.save()
            return redirect('users:profile_show', user.id)

        return render(request, self.template_name, self.get_context_data(user_form=user_form, userprofile_form=userprofile_form))


class ProfileUpdateView(ProfileTwoFormsView):
    tab = 'update'
    template_name = 'users/profile_update.html'
    user_form_class = forms.UserForm
    userprofile_form_class = forms.UserProfileForm

    def get_context_data(self, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(**kwargs)
        context['page_title'] = _('Update profile')
        return context


class ProfilePasswordView(BaseProfileView, generic.View):
    tab = 'password'
    template_name = 'users/profile_password.html'

    def get(self, request, user):
        form = auth.forms.AdminPasswordChangeForm(user)
        return render(request, self.template_name, self.get_context_data(form=form))

    def post(self, request, user):
        form = auth.forms.AdminPasswordChangeForm(user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:profile_show', user.id)
        return render(request, self.template_name, self.get_context_data(form=form))


class ProfilePermissionsView(ProfileTwoFormsView):
    tab = 'permissions'
    template_name = 'users/profile_update.html'
    user_form_class = forms.UserPermissionsForm
    userprofile_form_class = forms.UserProfilePermissionsForm

    def get_context_data(self, **kwargs):
        context = super(ProfilePermissionsView, self).get_context_data(**kwargs)
        context['page_title'] = _('Permissions')
        return context

project/users/templates/users/base.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans 'Users' %}{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-3">
            <div class="btn-group" role="group" aria-label="...">
                <a class="btn btn-default{% if active_tab == 'folders' %} active {% endif %}" href="{% url 'users:show_folder' 'root' %}" role="button">
                    {% bootstrap_icon 'folder-open' %} <span class="ir-icon-label">{% trans 'Folders' %}</span>
                </a>
                <a class="btn btn-default{% if active_tab == 'search' %} active {% endif %}" href="{% url 'users:index' %}" role="button">
                    {% bootstrap_icon 'search' %} <span class="ir-icon-label">{% trans 'Search' %}</span>
                </a>
            </div>
            {% block sidebar %}
            {% endblock %}
        </div>
        <div class="col-md-9">
            {% block main %}
            {% endblock %}
        </div>
    </div>
{% endblock %}

project/users/templates/users/create_form.html
{% extends "users/base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_folders %}

{% block sidebar %}
    {% trans "Users" as root_name %}
    {% irunner_folders_tree cached_trees 'users:show_folder' folder_id root_name %}
{% endblock %}

{% block main %}
    {% trans "Users" as root_name %}
    {% irunner_folders_breadcrumbs cached_trees 'users:show_folder' folder_id root_name %}

    {% if form_name %}
        <h3>
            {{ form_name }}
            <small>
            {% if folder %}
                {% blocktrans with nn=folder.name %}inside ‘{{ nn }}’{% endblocktrans %}
            {% else %}
                {% trans 'in the root folder' %}
            {% endif %}
            </small>
        </h3>
    {% endif %}
    <form method="post" autocomplete="off">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-default">
                {% trans 'Save' %}
            </button>
            <a href="{% irunner_folders_url 'users:show_folder' folder_id %}" class="btn btn-default">
                {% trans 'Cancel' %}
            </a>
        {% endbuttons %}
    </form>
{% endblock %}

project/users/templates/users/delete.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_mass %}
{% load irunner_users %}

{% block title %}{% trans 'Users' %}{% endblock %}

{% block content %}
    {% if object_list %}
        {% trans 'Are you sure you want to delete the users?' %}
        <ul>
        {% for user in object_list %}
            <li><tt>{{ user.username }}</tt>&nbsp;&mdash; {% irunner_users_show user %}
        {% endfor %}
        </ul>

        <form method="post" autocomplete="off">
            {% csrf_token %}
            {% irunner_mass_hidden ids next %}
            {% buttons %}
                <button type="submit" class="btn btn-default">
                    {% trans 'Confirm' %}
                </button>
                {% if next %}
                    <a href="{{ next }}" class="btn btn-default">
                        {% trans 'Cancel' %}
                    </a>
                {% endif %}
            {% endbuttons %}
        </form>
    {% else %}
        {% trans 'No users selected' %}
    {% endif %}
{% endblock %}

project/users/templates/users/delete_folder.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_folders %}

{% block title %}{% trans 'Users' %}{% endblock %}

{% block content %}
    {% trans "Users" as root %}
    <div class="row">
        <div class="col-md-3">
            {% irunner_folders_tree cached_trees 'users:show_folder' folder_id root %}
        </div>
        <div class="col-md-9">
            {% irunner_folders_breadcrumbs cached_trees 'users:show_folder' folder_id root %}
            <h3>
                {% trans 'Create new folder' %}
                {% if cur_folder %}
                    <small>
                        &nbsp;{% blocktrans with nn=cur_folder.name %}inside ‘{{ nn }}’{% endblocktrans %}
                    </small>
                {% endif %}
            </h3>
            <form method="post" autocomplete="off">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-default">
                        {% trans 'Save' %}
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

project/users/templates/users/folder.html
{% extends "users/base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_folders %}
{% load irunner_pagination %}
{% load irunner_users %}

{% block sidebar %}
    {% trans "Users" as root_name %}
    {% irunner_folders_tree cached_trees 'users:show_folder' folder_id root_name %}
{% endblock %}

{% block main %}
    {% trans "Users" as root_name %}
    {% irunner_folders_breadcrumbs cached_trees 'users:show_folder' folder_id root_name %}
    <p>
        <a class="btn btn-default btn-sm" href="{% irunner_folders_url 'users:create_folder' folder_id %}" role="button">
            {% bootstrap_icon 'folder-open' %} <span class="ir-icon-label">{% trans 'Create folder' %}</span>
        </a>

        {% if can_delete_folder %}
            <a class="btn btn-default btn-sm" href="#" role="button">
                {% bootstrap_icon 'trash' %} <span class="ir-icon-label">{% trans 'Delete folder' %}</span>
            </a>
        {% endif %}

        <a class="btn btn-default btn-sm" href="{% irunner_folders_url 'users:create_user' folder_id %}" role="button">
            {% bootstrap_icon 'user' %} <span class="ir-icon-label">{% trans 'Create user' %}</span>
        </a>

        <a class="btn btn-default btn-sm" href="{% irunner_folders_url 'users:create_users_mass' folder_id %}" role="button">
            {% bootstrap_icon 'list' %} <span class="ir-icon-label">{% trans 'Mass registration' %}</span>
        </a>

        {% if has_users %}

            <button onclick="irPerformActionOnSelected('{% url 'users:move' %}', '{{ request.path }}', '{% trans 'No users selected' %}')" class="btn btn-default btn-sm">
                {% bootstrap_icon 'ok' %}&nbsp;{% bootstrap_icon 'transfer' %} <span class="ir-icon-label">{% trans 'Move' %}</span>
            </button>

            <button onclick="irPerformActionOnSelected('{% url 'users:delete' %}', '{{ request.path }}', '{% trans 'No users selected' %}')" class="btn btn-default btn-sm">
                {% bootstrap_icon 'ok' %}&nbsp;{% bootstrap_icon 'trash' %} <span class="ir-icon-label">{% trans 'Delete' %}</span>
            </button>

        {% endif %}
    </p>
    {% irunner_folders_subfolders cached_trees 'users:show_folder' folder_id %}

    <div class="panel panel-default">
        <div class="panel-body">
            {% if object_list %}
                {% irunner_users_list object_list pagination_context show_checkbox=True %}
            {% else %}
                <div class="ir-absence">
                    {% trans 'There are no users in the folder' %}
                </div>
            {% endif %}
        </div>
    </div>
    <script>
    $(document).ready(function () {
        irSetUpSelectAll();
    });
    </script>
{% endblock %}

project/users/templates/users/index.html
{% extends "users/base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_users %}
{% load widget_tweaks %}

{% block main %}
    <ol class="breadcrumb">
        <li>{% trans 'User search' %}</li>
    </ol>

    <form method="get" autocomplete="off">
        <div class="form-group">
            <div class="input-group">
                {% trans 'Search for...' as search_for %}
                {% render_field form.query type="search" class="form-control" placeholder=search_for %}
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit">{% bootstrap_icon 'search' %}</button>
                </span>
            </div>
        </div>
        <div class="checkbox">
            <label>
                {{ form.staff }}{{ form.staff.label }}
            </label>
        </div>
    </form>

    <div class="panel panel-default">
        <div class="panel-body">
            {% if object_list %}
                {% irunner_users_list object_list pagination_context show_folder=True %}
            {% else %}
                <div class="ir-absence">
                    {% trans 'No users found.' %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

project/users/templates/users/irunner_users_list_tag.html
{% load i18n %}
{% load irunner_users %}
{% load irunner_pagination %}

{% if pagination_context %}
    {% irunner_pagination pagination_context %}
{% endif %}

<table class="table table-condensed">
    <thead>
        <tr>
            {% if show_checkbox %}
                <th><input type="checkbox" id="selectall"></th>
            {% endif %}
            <th>{% trans 'Username' %}</th>
            <th>{% trans 'Full name' context 'human' %}</th>
            <th>{% trans 'Last login' %}</th>
            {% if show_folder %}
                <th>{% trans 'Folder' %}</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
        {% for user in users %}
        <tr>
            {% if show_checkbox %}
                <td><input type="checkbox" class="ir-checkbox" name="{{ user.id }}"></td>
            {% endif %}
            <td class="ir-monospace"><a href="{% url 'users:profile_show' user.id %}">{{ user.username }}</a></td>
            <td>{% irunner_users_show user %}</td>
            <td>{% if user.last_login %}{{ user.last_login }}{% else %}&mdash;{% endif %}</td>
            {% if show_folder %}
                <td>
                {% with user.userprofile.folder as folder %}  
                    {% if user.userprofile.folder %}
                        <a href="{% url 'users:show_folder' folder.id %}">{{ folder }}</a>
                    {% else %}
                        <a href="{% url 'users:show_folder' 'root' %}">{% trans 'Users' %}</a>
                    {% endif %}
                {% endwith %}
                </td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

project/users/templates/users/irunner_users_show_tag.html
{% if user %}{{ user.first_name }}{% if user.last_name %} {{ user.last_name }}{% endif %}{% else %}&mdash;{% endif %}

project/users/templates/users/move.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}
{% load irunner_mass %}
{% load irunner_users %}

{% block title %}{% trans 'Users' %}{% endblock %}

{% block content %}
    {% if object_list %}
        {% trans 'Are you sure you want to move the users to another folder?' %}
        <ul>
        {% for userprofile in object_list %}
            <li><tt>{{ userprofile.user.username }}</tt>&nbsp;&mdash; {% irunner_users_show userprofile.user %}
        {% endfor %}
        </ul>

        <form method="post" autocomplete="off">
            {% csrf_token %}
            {% irunner_mass_hidden ids next %}
            {% bootstrap_form form %}
            {% buttons %}
                <button type="submit" class="btn btn-default">
                    {% trans 'Confirm' %}
                </button>
                {% if next %}
                    <a href="{{ next }}" class="btn btn-default">
                        {% trans 'Cancel' %}
                    </a>
                {% endif %}
            {% endbuttons %}
        </form>
    {% else %}
        {% trans 'No users selected' %}
    {% endif %}
{% endblock %}

project/users/templates/users/profile_base.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-md-3">
        {% include 'users/profile_sidebar.html' %}
    </div>
    <div class="col-md-9">
        {% block main %}
        {% endblock %}
    </div>
</div>
{% endblock %}

project/users/templates/users/profile_sidebar.html
{% load bootstrap3 %}
{% load i18n %}

{% load irunner_users %}

<div class="list-group ir-list-group-danger">
    <a href="{% url 'users:profile_show' edited_user.id %}" class="list-group-item list-group-item-danger{% if active_tab == 'show' %} active{% endif %}">
        {% bootstrap_icon 'user' %}
        <span class="ir-icon-label">{% irunner_users_show edited_user %}</span>
    </a>
    <a href="{% url 'users:profile_update' edited_user.id %}" class="list-group-item{% if active_tab == 'update' %} active{% endif %}">
        {% bootstrap_icon 'pencil' %}
        <span class="ir-icon-label">{% trans 'Update profile' %}</span>
    </a>
    <a href="{% url 'users:profile_password' edited_user.id %}" class="list-group-item{% if active_tab == 'password' %} active{% endif %}">
        {% bootstrap_icon 'asterisk' %}
        <span class="ir-icon-label">{% trans 'Change password' %}</span>
    </a>
    <a href="{% url 'users:profile_permissions' edited_user.id %}" class="list-group-item{% if active_tab == 'permissions' %} active{% endif %}">
        {% bootstrap_icon 'lock' %}
        <span class="ir-icon-label">{% trans 'Permissions' %}</span>
    </a>
</div>