project/api/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # ex: /polls/
    url(r'^fs/status$', views.FileStatusView.as_view(), name='fs_status'),
    url(r'^fs/(?P<filename>[0-9a-f]*)$', views.FileView.as_view(), name='fs_status'),
    url(r'^jobs/take$', views.JobTakeView.as_view(), name='take_job'),
    url(r'^jobs/(?P<job_id>\d+)/result$', views.JobPutResult.as_view()),
    url(r'^jobs/(?P<job_id>\d+)/state$', views.JobPutState.as_view()),
]

project/irunner2/urls.py
from django.conf.urls import include, url
#from django.contrib import admin
import common.views
from django_js_reverse.views import urls_js
from django.views.decorators.cache import cache_page


urlpatterns = [
    url(r'^$', common.views.home, name='home'),
    url(r'^language/$', common.views.language, name='language'),
    url(r'^feedback/', include('feedback.urls', namespace='feedback')),
    url(r'^i18n/', include('django.conf.urls.i18n'), name='set_language'),
    url(r'^storage/', include('storage.urls', namespace='storage')),
    url(r'^problems/', include('problems.urls', namespace='problems')),
    url(r'^compilers/', include('proglangs.urls', namespace='proglangs')),
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^', include('solutions.urls', namespace='solutions')),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^about/', common.views.about, name='about'),
    url('^', include('cauth.urls')),
    #url(r'^admin/', include(admin.site.urls)),
    url(r'^jsreverse/$', cache_page(3600)(urls_js), name='js_reverse'),
]

handler403 = 'common.views.error403'

project/proglangs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.CreateCompilerView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/$', views.UpdateCompilerView.as_view(), name='update'),
]

project/proglangs/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Compiler(models.Model):
    UNKNOWN = ''
    C = 'c'
    CPP = 'cpp'
    JAVA = 'java'
    PASCAL = 'pas'
    DELPHI = 'dpr'
    PYTHON = 'py'
    CSHARP = 'cs'

    LANGUAGE_CHOICES = (
        (UNKNOWN, _('Unknown')),
        (C, 'C'),
        (CPP, 'C++'),
        (JAVA, 'Java'),
        (PASCAL, 'Pascal'),
        (DELPHI, 'Delphi'),
        (PYTHON, 'Python'),
        (CSHARP, 'C#'),
    )

    handle = models.CharField(_('string identifier'), max_length=30, unique=True)
    language = models.CharField(_('language'), max_length=8, choices=LANGUAGE_CHOICES, default=UNKNOWN, blank=True)
    description = models.CharField(_('description'), max_length=255, blank=True)
    legacy = models.BooleanField(_('compiler is considered legacy'), default=False)

    def __unicode__(self):
        return self.description

    class Meta:
        ordering = ['description']

project/proglangs/views.py
from django.views.generic import ListView, CreateView, UpdateView
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext as _

from .models import Compiler


class IndexView(ListView):
    template_name = 'proglangs/index.html'
    context_object_name = 'compilers'

    def get_queryset(self):
        return Compiler.objects.all()


class CreateCompilerView(CreateView):
    model = Compiler
    template_name = 'proglangs/edit.html'
    fields = ['handle', 'language', 'description', 'legacy']

    def get_success_url(self):
        return reverse('proglangs:index')

    def get_context_data(self, **kwargs):
        context = super(CreateCompilerView, self).get_context_data(**kwargs)
        context['page_title'] = _('New compiler')
        return context


class UpdateCompilerView(UpdateView):
    model = Compiler
    template_name = 'proglangs/edit.html'
    fields = ['handle', 'language', 'description', 'legacy']

    def get_success_url(self):
        return reverse('proglangs:index')

    def get_context_data(self, **kwargs):
        context = super(UpdateCompilerView, self).get_context_data(**kwargs)
        context['page_title'] = u'{0} {1} ({2})'.format(_('Compiler'), self.object.handle, self.object.description)
        return context

project/proglangs/templates/proglangs/edit.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{{ page_title }}{% endblock %}

{% block content %}

<form method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
        <button type="submit" class="btn btn-default">{% trans 'Save' %}</button>
    {% endbuttons %}
</form>

{% endblock %}

project/proglangs/templates/proglangs/index.html
{% extends "base.html" %}

{% load i18n %}
{% load irunner_proglangs %}

{% block content %}

<h1>{% block title %}{% trans 'Compilers' %}{% endblock %}</h1>

<p>
    <a href="{% url 'proglangs:create' %}">{% trans 'New compiler' %}</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>{% trans 'String identifier' %}</th>
            <th>{% trans 'Description' %}</th>
            <th>{% trans 'Language' %}</th>
            <th>{% trans 'Legacy?' %}</th>
        </tr>
    </thead>
    <tbody>
    {% for compiler in compilers %}
        <tr {% if compiler.legacy %} class="active" {% endif %}>
            <td>{{ compiler.id }}</td>
            <td><a href="{% url 'proglangs:update' compiler.id %}">{{ compiler.handle }}</a></td>
            <td>{{ compiler.description }}</td>
            <td>{% irunner_proglangs_compilerbox compiler tooltip=False %}</td>
            <td>{{ compiler.legacy|yesno }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

{% endblock %}

project/proglangs/templates/proglangs/irunner_proglangs_compilerbox_tag.html
<div class="ir-box ir-langbox ir-langbox-{{ compiler.language }}"{% if tooltip %} title="{{ compiler.description }}"{% endif %}>{{ compiler.get_language_display }}</div>